import Mathlib.Tactic
import TLLC.Process.Step
import TLLC.Process.CSubst
import TLLC.Dynamic.Occurs

/-!
# Soup normal forms: a complete characterization of structural congruence

Every process is structurally congruent to a *prenex form* `ν … ν (m₁ | ⋯ | mₙ)` — a "soup" of
threads under a block of restrictions. This file computes that form (`prenex`), packages it as a
`Config` (binder count + thread list), and characterizes structural congruence `≡ₚ` as the
equivalence `SoupEquiv` generated by four configuration moves:

* permuting the thread list (`par_sym`/`assoc`),
* pointwise term congruence `CongrTerm .ex` on threads (`tm`),
* adding/removing a garbage thread `pure ()` (`end`),
* transposing two binders (`exch` conjugated under restrictions).

The binder count of a configuration is *invariant* under `≡ₚ`: no congruence rule creates or
discards a restriction. This is the load-bearing fact that makes the characterization possible.

The characterization (`congruence_iff_soup`) is the engine of the reflection theorem
(`TLLC/Spawning/Reflection.lean`): `Process.Step` may rearrange a process by an arbitrary
congruence before firing a redex, and inverting that rearrangement against the flattening of a
spawning tree requires knowing that congruence can only permute threads and binders, adjust
implicit positions, and shuffle garbage.

Conventions. In a configuration `(k, ts)`, channel index `i < k` of a thread refers to the
`(i+1)`-th innermost restriction of `soupForm (k, ts) = ν^k (…)`, and index `k + c` refers to the
ambient free channel `c`. In `prenex (par p q)`, the binders of `p` keep indices `0 … kp-1` and the
binders of `q` are relocated to `kp … kp+kq-1`.
-/

namespace TLLC.Process
open Autosubst Autosubst.Notation
open TLLC.Dynamic
open scoped TLLC.Static TLLC.Dynamic

/-! ## Configurations and the prenex computation -/

/-- A prenex configuration: number of ν-binders and the thread soup. -/
abbrev Config := Nat × List Term

/-- Identity below `k`, shift by `n` at and above `k`. Relocates a term's free channels when the
term is placed under `n` extra binders that sit *outside* binder block `[0, k)`. -/
def shiftAbove (k n : Nat) (x : Nat) : Nat := if x < k then x else x + n

/-- Transposition of the channel indices `i` and `j`. -/
def cswap (i j : Nat) (x : Nat) : Nat :=
  if x = i then j else if x = j then i else x

/-- Lift a renaming of the free channels of a process over its `k` extracted binders: identity
below `k`, `k + ξ c` at `k + c`. -/
def liftBinders (k : Nat) (ξ : Nat → Nat) (x : Nat) : Nat :=
  if x < k then x else k + ξ (x - k)

lemma shiftAbove_lt {k n x : Nat} (h : x < k) : shiftAbove k n x = x := if_pos h

lemma shiftAbove_ge {k n x : Nat} (h : k ≤ x) : shiftAbove k n x = x + n :=
  if_neg (by omega)

lemma cswap_left {i j : Nat} : cswap i j i = j := if_pos rfl

lemma cswap_right {i j : Nat} : cswap i j j = i := by
  by_cases h : j = i
  · subst h; exact if_pos rfl
  · exact (if_neg h).trans (if_pos rfl)

lemma cswap_ne {i j x : Nat} (hi : x ≠ i) (hj : x ≠ j) : cswap i j x = x :=
  (if_neg hi).trans (if_neg hj)

lemma cswap_invol (i j x : Nat) : cswap i j (cswap i j x) = x := by
  by_cases hi : x = i
  · subst hi; rw [cswap_left, cswap_right]
  · by_cases hj : x = j
    · subst hj; rw [cswap_right, cswap_left]
    · rw [cswap_ne hi hj, cswap_ne hi hj]

lemma liftBinders_lt {k x : Nat} (ξ : Nat → Nat) (h : x < k) : liftBinders k ξ x = x :=
  if_pos h

lemma liftBinders_ge {k x : Nat} (ξ : Nat → Nat) (h : k ≤ x) :
    liftBinders k ξ x = k + ξ (x - k) := if_neg (by omega)

/-- Rotate the index block `[a, a + n]` up by one position: `a ↦ a + n`, `(a, a + n] ↦ · - 1`. -/
def rotUp (a n : Nat) (x : Nat) : Nat :=
  if x = a then a + n else if a < x ∧ x ≤ a + n then x - 1 else x

/-- Inverse of `rotUp`. -/
def rotDown (a n : Nat) (x : Nat) : Nat :=
  if x = a + n then a else if a ≤ x ∧ x < a + n then x + 1 else x

lemma rotDown_rotUp (a n x : Nat) : rotDown a n (rotUp a n x) = x := by
  unfold rotUp rotDown; split_ifs <;> omega

lemma rotUp_rotDown (a n x : Nat) : rotUp a n (rotDown a n x) = x := by
  unfold rotUp rotDown; split_ifs <;> omega

lemma rotUp_lt {a n x : Nat} (h : x < a) : rotUp a n x = x := by
  unfold rotUp; split_ifs <;> omega

lemma rotUp_base (a n : Nat) : rotUp a n a = a + n := if_pos rfl

lemma rotUp_mid {a n x : Nat} (h1 : a < x) (h2 : x ≤ a + n) : rotUp a n x = x - 1 := by
  unfold rotUp; split_ifs <;> omega

lemma rotUp_hi {a n x : Nat} (h : a + n < x) : rotUp a n x = x := by
  unfold rotUp; split_ifs <;> omega

/-- Exchange the index blocks `[0, m)` and `[m, m + n)`. -/
def blockSwap (m n : Nat) (x : Nat) : Nat :=
  if x < m then x + n else if x < m + n then x - m else x

lemma blockSwap_blockSwap (m n x : Nat) : blockSwap n m (blockSwap m n x) = x := by
  unfold blockSwap; split_ifs <;> omega

lemma blockSwap_lo {m n x : Nat} (h : x < m) : blockSwap m n x = x + n := if_pos h

lemma blockSwap_mid {m n x : Nat} (h1 : m ≤ x) (h2 : x < m + n) : blockSwap m n x = x - m := by
  unfold blockSwap; split_ifs <;> omega

lemma blockSwap_hi {m n x : Nat} (h : m + n ≤ x) : blockSwap m n x = x := by
  unfold blockSwap; split_ifs <;> omega

/-- Compute the prenex form of a process: extract all restrictions, leaving the soup of threads.
The binders of the left component of a `par` keep their indices; the right component's binders are
relocated on top of them. A `nu`'s binder receives index `kp` (just above its body's binders). -/
def prenex : Proc → Config
  | .tm m => (0, [m])
  | .par p q =>
      let (kp, tsp) := prenex p
      let (kq, tsq) := prenex q
      (kp + kq,
        tsp.map (fun m => m⟨shiftAbove kp kq; (id : Nat → Nat)⟩) ++
        tsq.map (fun m => m⟨(· + kp); (id : Nat → Nat)⟩))
  | .nu p =>
      let (kp, tsp) := prenex p
      (kp + 1, tsp)

/-- Compose two configurations the way `prenex` composes `par`. -/
def parConfig (c d : Config) : Config :=
  (c.1 + d.1,
    c.2.map (fun m => m⟨shiftAbove c.1 d.1; (id : Nat → Nat)⟩) ++
    d.2.map (fun m => m⟨(· + c.1); (id : Nat → Nat)⟩))

/-- Compose a configuration the way `prenex` handles `nu`. -/
def nuConfig (c : Config) : Config := (c.1 + 1, c.2)

@[simp] lemma prenex_tm (m : Term) : prenex (.tm m) = (0, [m]) := rfl

@[simp] lemma prenex_par (p q : Proc) :
    prenex (.par p q) = parConfig (prenex p) (prenex q) := rfl

@[simp] lemma prenex_nu (p : Proc) : prenex (.nu p) = nuConfig (prenex p) := rfl

/-- A block of `k` restrictions. -/
def nuN : Nat → Proc → Proc
  | 0, p => p
  | k + 1, p => .nu (nuN k p)

@[simp] lemma nuN_zero (p : Proc) : nuN 0 p = p := rfl

@[simp] lemma nuN_succ (k : Nat) (p : Proc) : nuN (k + 1) p = .nu (nuN k p) := rfl

/-- The thread soup as a process, seeded with a garbage thread so the empty soup is meaningful. -/
def soupThreads (ts : List Term) : Proc :=
  ts.foldl (fun acc m => .par acc (.tm m)) (.tm (.pure .one))

/-- The process denoted by a configuration. -/
def soupForm (c : Config) : Proc := nuN c.1 (soupThreads c.2)

/-! ## Renaming algebra -/

/-- Channel renamings of terms are extensional. -/
lemma tren_ext (m : Term) {ξ ζ : Nat → Nat} (h : ∀ x, ξ x = ζ x) :
    m⟨ξ; (id : Nat → Nat)⟩ = m⟨ζ; (id : Nat → Nat)⟩ := by
  rw [funext h]

/-- Channel renamings of terms compose. -/
lemma tren_comp (m : Term) (ξ ζ : Nat → Nat) :
    (m⟨ξ; (id : Nat → Nat)⟩)⟨ζ; (id : Nat → Nat)⟩ =
      m⟨fun x => ζ (ξ x); (id : Nat → Nat)⟩ := by
  asimp

/-- The identity channel renaming is the identity. -/
lemma tren_id (m : Term) : m⟨(id : Nat → Nat); (id : Nat → Nat)⟩ = m := by
  asimp

lemma tsmap_ext (ts : List Term) {ξ ζ : Nat → Nat} (h : ∀ x, ξ x = ζ x) :
    ts.map (fun m => m⟨ξ; (id : Nat → Nat)⟩) = ts.map (fun m => m⟨ζ; (id : Nat → Nat)⟩) := by
  rw [funext h]

lemma tsmap_comp (ts : List Term) (ξ ζ : Nat → Nat) :
    (ts.map (fun m => m⟨ξ; (id : Nat → Nat)⟩)).map (fun m => m⟨ζ; (id : Nat → Nat)⟩) =
      ts.map (fun m => m⟨fun x => ζ (ξ x); (id : Nat → Nat)⟩) := by
  rw [List.map_map]
  exact List.map_congr_left (fun m _ => tren_comp m ξ ζ)

lemma tsmap_id (ts : List Term) :
    ts.map (fun m => m⟨(id : Nat → Nat); (id : Nat → Nat)⟩) = ts := by
  rw [List.map_congr_left (fun m _ => tren_id m)]
  simp

/-! ## The soup equivalence -/

/-- One-step configuration moves generating the image of structural congruence. -/
inductive SoupG : Config → Config → Prop where
  /-- Permute the thread soup (`par_sym` / `assoc`). -/
  | perm {k ts ts'} :
    List.Perm ts ts' →
    SoupG (k, ts) (k, ts')
  /-- Pointwise structural congruence of threads (`tm`). -/
  | congr {k ts ts'} :
    List.Forall₂ (CongrTerm .ex) ts ts' →
    SoupG (k, ts) (k, ts')
  /-- Add a garbage thread (`end`, right-to-left). -/
  | garbage {k ts} :
    SoupG (k, ts) (k, .pure .one :: ts)
  /-- Transpose two binders (`exch` conjugated under restrictions). -/
  | swap {k ts} (i j : Nat) :
    i < k →
    j < k →
    SoupG (k, ts) (k, ts.map (fun m => m⟨cswap i j; (id : Nat → Nat)⟩))

/-- The soup equivalence: conversion closure of the configuration moves. -/
abbrev SoupEquiv : Config → Config → Prop := ARS.Conv SoupG

lemma SoupG.fst_eq {c c'} (h : SoupG c c') : c.1 = c'.1 := by
  cases h <;> rfl

/-- The binder count is invariant under the soup equivalence (and hence under `≡ₚ`). -/
lemma SoupEquiv.fst_eq {c c'} (h : SoupEquiv c c') : c.1 = c'.1 := by
  induction h with
  | refl => rfl
  | tail _ h ih => exact ih.trans h.fst_eq
  | taili _ h ih => exact ih.trans h.fst_eq.symm

/-! ## Basic soup moves -/

lemma SoupEquiv.perm {k ts ts'} (h : List.Perm ts ts') :
    SoupEquiv (k, ts) (k, ts') :=
  ARS.conv1 (SoupG.perm h)

lemma SoupEquiv.congr {k ts ts'} (h : List.Forall₂ (CongrTerm .ex) ts ts') :
    SoupEquiv (k, ts) (k, ts') :=
  ARS.conv1 (SoupG.congr h)

lemma SoupEquiv.garbage {k ts} : SoupEquiv (k, ts) (k, .pure .one :: ts) :=
  ARS.conv1 SoupG.garbage

lemma SoupEquiv.swap {k ts} (i j : Nat) (hi : i < k) (hj : j < k) :
    SoupEquiv (k, ts) (k, ts.map (fun m => m⟨cswap i j; (id : Nat → Nat)⟩)) :=
  ARS.conv1 (SoupG.swap i j hi hj)

private lemma SoupEquiv.ren_bounded {k : Nat} (n : Nat) (hn : n ≤ k) :
    ∀ (ts : List Term) (ξ ζ : Nat → Nat),
      (∀ x, ζ (ξ x) = x) → (∀ x, ξ (ζ x) = x) → (∀ x, n ≤ x → ξ x = x) →
      SoupEquiv (k, ts) (k, ts.map (fun m => m⟨ξ; (id : Nat → Nat)⟩)) := by
  induction n with
  | zero =>
      intro ts ξ ζ _ _ hfix
      have hid : ts.map (fun m => m⟨ξ; (id : Nat → Nat)⟩) = ts := by
        rw [tsmap_ext ts (ζ := (id : Nat → Nat)) (fun x => hfix x (Nat.zero_le x)), tsmap_id]
      rw [hid]
      exact ARS.Conv.refl
  | succ n ih =>
      intro ts ξ ζ hζξ hξζ hfix
      by_cases hfixn : ξ n = n
      · refine ih (by omega) ts ξ ζ hζξ hξζ ?_
        intro x hx
        rcases Nat.eq_or_lt_of_le hx with rfl | h'
        · exact hfixn
        · exact hfix x h'
      · have hξa : ξ (ζ n) = n := hξζ n
        have haltn : ζ n < n := by
          rcases Nat.lt_or_ge (ζ n) n with h | h
          · exact h
          · exfalso
            rcases Nat.eq_or_lt_of_le h with heq | h'
            · rw [← heq] at hξa
              exact hfixn hξa
            · have := hfix (ζ n) h'
              omega
        have step1 : SoupEquiv (k, ts) (k, ts.map (fun m => m⟨cswap (ζ n) n; (id : Nat → Nat)⟩)) :=
          SoupEquiv.swap (ζ n) n (by omega) (by omega)
        have step2 : SoupEquiv (k, ts.map (fun m => m⟨cswap (ζ n) n; (id : Nat → Nat)⟩))
            (k, (ts.map (fun m => m⟨cswap (ζ n) n; (id : Nat → Nat)⟩)).map
              (fun m => m⟨fun x => ξ (cswap (ζ n) n x); (id : Nat → Nat)⟩)) := by
          refine ih (by omega) _ (fun x => ξ (cswap (ζ n) n x))
            (fun x => cswap (ζ n) n (ζ x)) ?_ ?_ ?_
          · intro x
            show cswap (ζ n) n (ζ (ξ (cswap (ζ n) n x))) = x
            rw [hζξ (cswap (ζ n) n x), cswap_invol]
          · intro x
            show ξ (cswap (ζ n) n (cswap (ζ n) n (ζ x))) = x
            rw [cswap_invol, hξζ]
          · intro x hx
            rcases Nat.eq_or_lt_of_le hx with rfl | h'
            · show ξ (cswap (ζ n) n n) = n
              rw [cswap_right, hξa]
            · show ξ (cswap (ζ n) n x) = x
              rw [cswap_ne (by omega) (by omega), hfix x h']
        have hcomp : (ts.map (fun m => m⟨cswap (ζ n) n; (id : Nat → Nat)⟩)).map
            (fun m => m⟨fun x => ξ (cswap (ζ n) n x); (id : Nat → Nat)⟩) =
            ts.map (fun m => m⟨ξ; (id : Nat → Nat)⟩) := by
          rw [tsmap_comp]
          exact tsmap_ext ts (fun x => by rw [cswap_invol])
        rw [hcomp] at step2
        exact ARS.conv_trans step1 step2

/-- Apply an arbitrary renaming that is a bijection below `k` (and the identity at and above `k`):
realized by a chain of binder transpositions. -/
lemma SoupEquiv.ren {k ts} (ξ ζ : Nat → Nat)
    (hζξ : ∀ x, ζ (ξ x) = x) (hξζ : ∀ x, ξ (ζ x) = x)
    (hfix : ∀ x, k ≤ x → ξ x = x) :
    SoupEquiv (k, ts) (k, ts.map (fun m => m⟨ξ; (id : Nat → Nat)⟩)) :=
  SoupEquiv.ren_bounded k (Nat.le_refl k) ts ξ ζ hζξ hξζ hfix

/-! ## Compositionality of the soup equivalence -/

lemma upRen_CC_zero (ξ : Nat → Nat) : upRen_Chan_Chan ξ 0 = 0 := by
  asimp

lemma upRen_CC_succ (ξ : Nat → Nat) (n : Nat) : upRen_Chan_Chan ξ (n + 1) = ξ n + 1 := by
  asimp

/-- Lifting the binder block over a lifted renaming widens the block. -/
lemma liftBinders_upRen (k : Nat) (ξ : Nat → Nat) :
    ∀ x, liftBinders k (upRen_Chan_Chan ξ) x = liftBinders (k + 1) ξ x := by
  intro x
  rcases Nat.lt_or_ge x k with h | h
  · rw [liftBinders_lt _ h, liftBinders_lt _ (by omega)]
  · rcases Nat.eq_or_lt_of_le h with rfl | h'
    · rw [liftBinders_ge _ h, liftBinders_lt _ (by omega)]
      rw [show k - k = 0 from by omega, upRen_CC_zero]
      omega
    · rw [liftBinders_ge _ h, liftBinders_ge _ (by omega)]
      rw [show x - k = (x - (k + 1)) + 1 from by omega, upRen_CC_succ]
      omega

/-- Free-index renaming commutes with placing a term under `kq` outer binders. -/
lemma liftBinders_shiftAbove (kp kq : Nat) (ξ : Nat → Nat) :
    ∀ x, shiftAbove kp kq (liftBinders kp ξ x) = liftBinders (kp + kq) ξ (shiftAbove kp kq x) := by
  intro x
  rcases Nat.lt_or_ge x kp with h | h
  · rw [liftBinders_lt _ h, shiftAbove_lt h, liftBinders_lt _ (by omega)]
  · rw [liftBinders_ge _ h, shiftAbove_ge (by omega), shiftAbove_ge h,
      liftBinders_ge _ (by omega), show x + kq - (kp + kq) = x - kp from by omega]
    omega

/-- Free-index renaming commutes with relocating a term's binders on top of `kp` others. -/
lemma liftBinders_addBase (kp kq : Nat) (ξ : Nat → Nat) :
    ∀ x, liftBinders kq ξ x + kp = liftBinders (kp + kq) ξ (x + kp) := by
  intro x
  rcases Nat.lt_or_ge x kq with h | h
  · rw [liftBinders_lt _ h, liftBinders_lt _ (by omega)]
  · rw [liftBinders_ge _ h, liftBinders_ge _ (by omega),
      show x + kp - (kp + kq) = x - kq from by omega]
    omega

/-- `prenex` commutes with channel renaming: the binders are untouched and the renaming acts on
the free indices. -/
lemma prenex_cren (p : Proc) (ξ : Nat → Nat) :
    prenex (p⟨ξ; (id : Nat → Nat)⟩) =
      ((prenex p).1,
        (prenex p).2.map (fun m => m⟨liftBinders (prenex p).1 ξ; (id : Nat → Nat)⟩)) := by
  induction p generalizing ξ with
  | tm m =>
      asimp
      simp [prenex]
      exact tren_ext m (fun x => by simp [liftBinders])
  | par p q ihp ihq =>
      asimp
      rw [prenex_par, prenex_par, ihp, ihq]
      simp only [parConfig, List.map_append]
      congr 1
      rw [tsmap_comp, tsmap_comp, tsmap_comp, tsmap_comp]
      congr 1
      · exact tsmap_ext _ (liftBinders_shiftAbove (prenex p).1 (prenex q).1 ξ)
      · exact tsmap_ext _ (liftBinders_addBase (prenex p).1 (prenex q).1 ξ)
  | nu p ihp =>
      asimp
      rw [prenex_nu, prenex_nu, ihp]
      simp only [nuConfig]
      congr 1
      exact tsmap_ext _ (liftBinders_upRen (prenex p).1 ξ)

lemma tren_pure_one (ξ : Nat → Nat) :
    (Term.pure .one)⟨ξ; (id : Nat → Nat)⟩ = Term.pure .one := by
  asimp

lemma forall₂_congr_map (ξ : Nat → Nat) {ts ts' : List Term}
    (h : List.Forall₂ (CongrTerm .ex) ts ts') :
    List.Forall₂ (CongrTerm .ex) (ts.map (fun m => m⟨ξ; (id : Nat → Nat)⟩))
      (ts'.map (fun m => m⟨ξ; (id : Nat → Nat)⟩)) := by
  induction h with
  | nil => exact List.Forall₂.nil
  | cons hm _ ih => exact List.Forall₂.cons (hm.crename ξ) ih

lemma forall₂_congr_refl (ts : List Term) :
    List.Forall₂ (CongrTerm .ex) ts ts := by
  induction ts with
  | nil => exact List.Forall₂.nil
  | cons m ts ih => exact List.Forall₂.cons (CongrTerm.refl .ex m) ih

lemma forall₂_append {R : Term → Term → Prop} {l₁ l₂ u₁ u₂ : List Term}
    (hl : List.Forall₂ R l₁ l₂) (hu : List.Forall₂ R u₁ u₂) :
    List.Forall₂ R (l₁ ++ u₁) (l₂ ++ u₂) := by
  induction hl with
  | nil => simpa using hu
  | cons hm _ ih => exact List.Forall₂.cons hm ih

lemma SoupG.parConfig_left {c c' : Config} (d : Config) (h : SoupG c c') :
    SoupEquiv (parConfig c d) (parConfig c' d) := by
  cases h with
  | @perm k ts ts' hperm =>
      simp only [parConfig]
      exact SoupEquiv.perm ((hperm.map _).append_right _)
  | @congr k ts ts' hcongr =>
      simp only [parConfig]
      exact SoupEquiv.congr
        (forall₂_append (forall₂_congr_map _ hcongr) (forall₂_congr_refl _))
  | @garbage k ts =>
      simp only [parConfig, List.map_cons, tren_pure_one, List.cons_append]
      exact SoupEquiv.garbage
  | @swap k ts i j hi hj =>
      simp only [parConfig]
      have key : (ts.map (fun m => m⟨cswap i j; (id : Nat → Nat)⟩)).map
            (fun m => m⟨shiftAbove k d.1; (id : Nat → Nat)⟩) ++
            d.2.map (fun m => m⟨(· + k); (id : Nat → Nat)⟩) =
          (ts.map (fun m => m⟨shiftAbove k d.1; (id : Nat → Nat)⟩) ++
            d.2.map (fun m => m⟨(· + k); (id : Nat → Nat)⟩)).map
            (fun m => m⟨cswap i j; (id : Nat → Nat)⟩) := by
        rw [List.map_append, tsmap_comp, tsmap_comp, tsmap_comp]
        congr 1
        · refine tsmap_ext ts (fun x => ?_)
          rcases Nat.lt_or_ge x k with hx | hx
          · have hcx : cswap i j x < k := by
              unfold cswap; split_ifs <;> omega
            rw [shiftAbove_lt hcx, shiftAbove_lt hx]
          · rw [cswap_ne (by omega) (by omega), shiftAbove_ge hx,
              cswap_ne (by omega) (by omega)]
        · refine tsmap_ext d.2 (fun y => ?_)
          exact (cswap_ne (by omega) (by omega)).symm
      rw [key]
      exact SoupEquiv.swap i j (by omega) (by omega)

lemma SoupG.parConfig_right (c : Config) {d d' : Config} (h : SoupG d d') :
    SoupEquiv (parConfig c d) (parConfig c d') := by
  cases h with
  | @perm k ts ts' hperm =>
      simp only [parConfig]
      exact SoupEquiv.perm ((hperm.map _).append_left _)
  | @congr k ts ts' hcongr =>
      simp only [parConfig]
      exact SoupEquiv.congr
        (forall₂_append (forall₂_congr_refl _) (forall₂_congr_map _ hcongr))
  | @garbage k ts =>
      simp only [parConfig, List.map_cons, tren_pure_one]
      refine ARS.conv_trans SoupEquiv.garbage (SoupEquiv.perm ?_)
      exact List.perm_middle.symm
  | @swap k ts i j hi hj =>
      simp only [parConfig]
      have key : c.2.map (fun m => m⟨shiftAbove c.1 k; (id : Nat → Nat)⟩) ++
            (ts.map (fun m => m⟨cswap i j; (id : Nat → Nat)⟩)).map
              (fun m => m⟨(· + c.1); (id : Nat → Nat)⟩) =
          (c.2.map (fun m => m⟨shiftAbove c.1 k; (id : Nat → Nat)⟩) ++
            ts.map (fun m => m⟨(· + c.1); (id : Nat → Nat)⟩)).map
            (fun m => m⟨cswap (i + c.1) (j + c.1); (id : Nat → Nat)⟩) := by
        rw [List.map_append, tsmap_comp, tsmap_comp, tsmap_comp]
        congr 1
        · refine tsmap_ext c.2 (fun x => ?_)
          rcases Nat.lt_or_ge x c.1 with hx | hx
          · rw [shiftAbove_lt hx, cswap_ne (by omega) (by omega)]
          · rw [shiftAbove_ge hx, cswap_ne (by omega) (by omega)]
        · refine tsmap_ext ts (fun y => ?_)
          by_cases hyi : y = i
          · subst hyi
            rw [cswap_left, cswap_left]
          · by_cases hyj : y = j
            · subst hyj
              rw [cswap_right, cswap_right]
            · rw [cswap_ne hyi hyj, cswap_ne (by omega) (by omega)]
      rw [key]
      exact SoupEquiv.swap (i + c.1) (j + c.1) (by omega) (by omega)

lemma SoupG.nuConfig {c c' : Config} (h : SoupG c c') :
    SoupG (nuConfig c) (nuConfig c') := by
  cases h with
  | perm hperm => exact SoupG.perm hperm
  | congr hcongr => exact SoupG.congr hcongr
  | garbage => exact SoupG.garbage
  | swap i j hi hj => exact SoupG.swap i j (by omega) (by omega)

lemma SoupEquiv.parConfig_left {c c' : Config} (d : Config) (h : SoupEquiv c c') :
    SoupEquiv (parConfig c d) (parConfig c' d) :=
  ARS.conv_img (fun c => parConfig c d) SoupG
    (fun _ _ h => SoupG.parConfig_left d h) c c' h

lemma SoupEquiv.parConfig_right (c : Config) {d d' : Config} (h : SoupEquiv d d') :
    SoupEquiv (parConfig c d) (parConfig c d') :=
  ARS.conv_img (fun d => parConfig c d) SoupG
    (fun _ _ h => SoupG.parConfig_right c h) d d' h

lemma SoupEquiv.parConfig_congr {c c' d d' : Config}
    (hc : SoupEquiv c c') (hd : SoupEquiv d d') :
    SoupEquiv (parConfig c d) (parConfig c' d') :=
  ARS.conv_trans (SoupEquiv.parConfig_left d hc) (SoupEquiv.parConfig_right c' hd)

lemma SoupEquiv.nuConfig_congr {c c' : Config} (h : SoupEquiv c c') :
    SoupEquiv (nuConfig c) (nuConfig c') :=
  ARS.conv_hom nuConfig SoupG (fun _ _ h => SoupG.nuConfig h) c c' h

/-! ## N2: structural congruence maps to the soup equivalence -/

lemma exch_ren_zero : exch_ren 0 = 1 := rfl

lemma exch_ren_one : exch_ren 1 = 0 := rfl

lemma exch_ren_add2 (n : Nat) : exch_ren (n + 2) = n + 2 := rfl

/-- Composing configurations is associative (the two prenex traversals of `assoc` agree). -/
lemma parConfig_assoc (c d e : Config) :
    parConfig c (parConfig d e) = parConfig (parConfig c d) e := by
  unfold parConfig
  refine Prod.ext (by simp only []; omega) ?_
  simp only [List.map_append]
  rw [← List.append_assoc, tsmap_comp, tsmap_comp, tsmap_comp, tsmap_comp]
  congr 1
  congr 1
  · refine tsmap_ext c.2 (fun x => ?_)
    simp only [shiftAbove]
    split_ifs <;> omega
  · refine tsmap_ext d.2 (fun x => ?_)
    simp only [shiftAbove]
    split_ifs <;> omega
  · refine tsmap_ext e.2 (fun y => ?_)
    omega

/-- Composing configurations is commutative up to the soup equivalence (`par_sym`). -/
lemma parConfig_comm (c d : Config) :
    SoupEquiv (parConfig c d) (parConfig d c) := by
  simp only [parConfig]
  rw [show d.1 + c.1 = c.1 + d.1 from Nat.add_comm d.1 c.1]
  have step1 := SoupEquiv.ren
    (k := c.1 + d.1)
    (ts := c.2.map (fun m => m⟨shiftAbove c.1 d.1; (id : Nat → Nat)⟩) ++
      d.2.map (fun m => m⟨(· + c.1); (id : Nat → Nat)⟩))
    (blockSwap c.1 d.1) (blockSwap d.1 c.1)
    (blockSwap_blockSwap c.1 d.1) (blockSwap_blockSwap d.1 c.1)
    (fun x hx => blockSwap_hi hx)
  have heq : (c.2.map (fun m => m⟨shiftAbove c.1 d.1; (id : Nat → Nat)⟩) ++
        d.2.map (fun m => m⟨(· + c.1); (id : Nat → Nat)⟩)).map
        (fun m => m⟨blockSwap c.1 d.1; (id : Nat → Nat)⟩) =
      c.2.map (fun m => m⟨(· + d.1); (id : Nat → Nat)⟩) ++
        d.2.map (fun m => m⟨shiftAbove d.1 c.1; (id : Nat → Nat)⟩) := by
    rw [List.map_append, tsmap_comp, tsmap_comp]
    congr 1
    · refine tsmap_ext c.2 (fun x => ?_)
      simp only [shiftAbove, blockSwap]
      split_ifs <;> omega
    · refine tsmap_ext d.2 (fun y => ?_)
      simp only [shiftAbove, blockSwap]
      split_ifs <;> omega
  rw [heq] at step1
  exact ARS.conv_trans step1 (SoupEquiv.perm List.perm_append_comm)

/-- Scope extrusion at configuration level: the restriction of the left component moves out over
the composition, rotating its binder past the right component's block. -/
lemma parConfig_scope (c d : Config) :
    SoupEquiv (parConfig (nuConfig c) d)
      (nuConfig (parConfig c
        (d.1, d.2.map (fun m => m⟨liftBinders d.1 (· + 1); (id : Nat → Nat)⟩)))) := by
  simp only [parConfig, nuConfig]
  rw [show c.1 + d.1 + 1 = c.1 + 1 + d.1 from by omega]
  have step1 := SoupEquiv.ren
    (k := c.1 + 1 + d.1)
    (ts := c.2.map (fun m => m⟨shiftAbove (c.1 + 1) d.1; (id : Nat → Nat)⟩) ++
      d.2.map (fun m => m⟨(· + (c.1 + 1)); (id : Nat → Nat)⟩))
    (rotUp c.1 d.1) (rotDown c.1 d.1)
    (rotDown_rotUp c.1 d.1) (rotUp_rotDown c.1 d.1)
    (fun x hx => rotUp_hi (by omega))
  have heq : (c.2.map (fun m => m⟨shiftAbove (c.1 + 1) d.1; (id : Nat → Nat)⟩) ++
        d.2.map (fun m => m⟨(· + (c.1 + 1)); (id : Nat → Nat)⟩)).map
        (fun m => m⟨rotUp c.1 d.1; (id : Nat → Nat)⟩) =
      c.2.map (fun m => m⟨shiftAbove c.1 d.1; (id : Nat → Nat)⟩) ++
        (d.2.map (fun m => m⟨liftBinders d.1 (· + 1); (id : Nat → Nat)⟩)).map
          (fun m => m⟨(· + c.1); (id : Nat → Nat)⟩) := by
    rw [List.map_append, tsmap_comp, tsmap_comp, tsmap_comp]
    congr 1
    · refine tsmap_ext c.2 (fun x => ?_)
      simp only [shiftAbove, rotUp]
      split_ifs <;> omega
    · refine tsmap_ext d.2 (fun y => ?_)
      simp only [liftBinders, rotUp]
      split_ifs <;> omega
  rw [heq] at step1
  exact step1

/-- Binder exchange at configuration level. -/
lemma nuConfig_exch (c : Config) :
    SoupEquiv (nuConfig (nuConfig c))
      (nuConfig (nuConfig
        (c.1, c.2.map (fun m => m⟨liftBinders c.1 exch_ren; (id : Nat → Nat)⟩)))) := by
  simp only [nuConfig]
  have step1 := SoupEquiv.swap (k := c.1 + 1 + 1) (ts := c.2) c.1 (c.1 + 1)
    (by omega) (by omega)
  have heq : c.2.map (fun m => m⟨cswap c.1 (c.1 + 1); (id : Nat → Nat)⟩) =
      c.2.map (fun m => m⟨liftBinders c.1 exch_ren; (id : Nat → Nat)⟩) := by
    refine tsmap_ext c.2 (fun x => ?_)
    rcases Nat.lt_or_ge x c.1 with hx | hx
    · rw [cswap_ne (by omega) (by omega), liftBinders_lt _ hx]
    · rcases Nat.eq_or_lt_of_le hx with rfl | hx'
      · rw [cswap_left, liftBinders_ge _ (Nat.le_refl _),
          show c.1 - c.1 = 0 from by omega, exch_ren_zero]
      · rcases Nat.eq_or_lt_of_le hx' with heq1 | hx''
        · rw [← heq1, cswap_right, liftBinders_ge _ (by omega),
            show c.1 + 1 - c.1 = 1 from by omega, exch_ren_one]
          omega
        · rw [cswap_ne (by omega) (by omega), liftBinders_ge _ (by omega),
            show x - c.1 = (x - c.1 - 2) + 2 from by omega, exch_ren_add2]
          omega
  rw [heq] at step1
  exact step1

/-- Erasing a garbage thread at configuration level (`end`). -/
lemma parConfig_garbage (c : Config) :
    SoupEquiv (parConfig c (0, [Term.pure .one])) c := by
  simp only [parConfig, List.map_cons, List.map_nil, tren_pure_one]
  rw [show c.1 + 0 = c.1 from by omega]
  have heq : c.2.map (fun m => m⟨shiftAbove c.1 0; (id : Nat → Nat)⟩) = c.2 := by
    rw [tsmap_ext c.2 (ζ := (id : Nat → Nat)) (fun x => by
      simp only [shiftAbove, id_eq]
      split_ifs <;> omega), tsmap_id]
  rw [heq]
  refine ARS.conv_trans (SoupEquiv.perm (List.perm_append_singleton _ _)) ?_
  exact (ARS.conv1i SoupG.garbage : SoupEquiv (c.1, Term.pure .one :: c.2) (c.1, c.2))

/-- One-step structural congruence maps to the soup equivalence on prenex forms. -/
theorem congrProc_soup {P Q : Proc} (h : CongrProc P Q) :
    SoupEquiv (prenex P) (prenex Q) := by
  induction h with
  | @tm m m' hm =>
      exact SoupEquiv.congr (List.Forall₂.cons hm List.Forall₂.nil)
  | @par_sym p q =>
      rw [prenex_par, prenex_par]
      exact parConfig_comm (prenex p) (prenex q)
  | @assoc o p q =>
      rw [prenex_par, prenex_par, prenex_par, prenex_par, parConfig_assoc]
      exact ARS.Conv.refl
  | @scope p q =>
      rw [prenex_par, prenex_nu, prenex_nu, prenex_par, prenex_cren]
      exact parConfig_scope (prenex p) (prenex q)
  | @exch p =>
      rw [csubst_exch, prenex_nu, prenex_nu, prenex_nu, prenex_nu, prenex_cren]
      exact nuConfig_exch (prenex p)
  | @par p p' q q' _ _ ihp ihq =>
      rw [prenex_par, prenex_par]
      exact SoupEquiv.parConfig_congr ihp ihq
  | @res p p' _ ihp =>
      rw [prenex_nu, prenex_nu]
      exact SoupEquiv.nuConfig_congr ihp
  | @«end» p =>
      rw [prenex_par, prenex_tm]
      exact parConfig_garbage (prenex p)

/-- Structural congruence maps to the soup equivalence on prenex forms. -/
theorem congruence_soup {P Q : Proc} (h : P ≡ₚ Q) :
    SoupEquiv (prenex P) (prenex Q) :=
  ARS.conv_img prenex CongrProc (fun _ _ h => congrProc_soup h) P Q h

/-! ## Process-level soup-form algebra -/

lemma CongrProc.refl (p : Proc) : CongrProc p p := by
  induction p with
  | tm m => exact CongrProc.tm (CongrTerm.refl .ex m)
  | par p q ihp ihq => exact CongrProc.par ihp ihq
  | nu p ih => exact CongrProc.res ih

lemma congruence_par {p p' q q' : Proc} (hp : p ≡ₚ p') (hq : q ≡ₚ q') :
    Proc.par p q ≡ₚ Proc.par p' q' := by
  have h1 : Proc.par p q ≡ₚ Proc.par p' q :=
    ARS.conv_hom (fun p => Proc.par p q) CongrProc
      (fun _ _ h => CongrProc.par h (CongrProc.refl q)) p p' hp
  have h2 : Proc.par p' q ≡ₚ Proc.par p' q' :=
    ARS.conv_hom (fun q => Proc.par p' q) CongrProc
      (fun _ _ h => CongrProc.par (CongrProc.refl p') h) q q' hq
  exact ARS.conv_trans h1 h2

lemma congruence_res {p q : Proc} (h : p ≡ₚ q) : Proc.nu p ≡ₚ Proc.nu q :=
  ARS.conv_hom Proc.nu CongrProc (fun _ _ h => CongrProc.res h) p q h

lemma nuN_congr (k : Nat) {p q : Proc} (h : p ≡ₚ q) : nuN k p ≡ₚ nuN k q := by
  induction k with
  | zero => exact h
  | succ k ih => exact congruence_res ih

/-- Process channel renamings are extensional. -/
lemma pren_ext (p : Proc) {ξ ζ : Nat → Nat} (h : ∀ x, ξ x = ζ x) :
    p⟨ξ; (id : Nat → Nat)⟩ = p⟨ζ; (id : Nat → Nat)⟩ := by
  rw [funext h]

/-- Process channel renamings compose. -/
lemma pren_comp (p : Proc) (ξ ζ : Nat → Nat) :
    (p⟨ξ; (id : Nat → Nat)⟩)⟨ζ; (id : Nat → Nat)⟩ =
      p⟨fun x => ζ (ξ x); (id : Nat → Nat)⟩ := by
  asimp

/-- The identity channel renaming is the identity on processes. -/
lemma pren_id (p : Proc) : p⟨(id : Nat → Nat); (id : Nat → Nat)⟩ = p := by
  asimp

/-- Renaming a restriction block: the binders are untouched, the renaming lifts over them. -/
lemma nuN_cren (k : Nat) (p : Proc) (ξ : Nat → Nat) :
    (nuN k p)⟨ξ; (id : Nat → Nat)⟩ = nuN k (p⟨liftBinders k ξ; (id : Nat → Nat)⟩) := by
  induction k generalizing ξ with
  | zero =>
      simp only [nuN_zero]
      refine pren_ext p (fun x => ?_)
      rw [liftBinders_ge _ (Nat.zero_le x), Nat.sub_zero, Nat.zero_add]
  | succ k ih =>
      simp only [nuN_succ]
      asimp
      rw [ih, pren_ext p (liftBinders_upRen k ξ)]

/-- Merging two restriction blocks. -/
lemma nuN_comp (a b : Nat) (p : Proc) : nuN a (nuN b p) = nuN (a + b) p := by
  induction a with
  | zero => simp
  | succ a ih =>
      rw [show a + 1 + b = (a + b) + 1 from by omega, nuN_succ, nuN_succ, ih]

/-- Left fold of threads onto an accumulator process. -/
def parAllL (acc : Proc) (ts : List Term) : Proc :=
  ts.foldl (fun a m => .par a (.tm m)) acc

@[simp] lemma parAllL_nil (acc : Proc) : parAllL acc [] = acc := rfl

@[simp] lemma parAllL_cons (acc : Proc) (m : Term) (ts : List Term) :
    parAllL acc (m :: ts) = parAllL (.par acc (.tm m)) ts := rfl

lemma soupThreads_eq (ts : List Term) :
    soupThreads ts = parAllL (.tm (.pure .one)) ts := rfl

lemma soupThreads_append (l r : List Term) :
    soupThreads (l ++ r) = parAllL (soupThreads l) r := by
  rw [soupThreads_eq, soupThreads_eq, parAllL, parAllL, parAllL, List.foldl_append]

/-- Renaming distributes into the thread fold. -/
lemma parAllL_cren (acc : Proc) (ts : List Term) (ξ : Nat → Nat) :
    (parAllL acc ts)⟨ξ; (id : Nat → Nat)⟩ =
      parAllL (acc⟨ξ; (id : Nat → Nat)⟩) (ts.map (fun m => m⟨ξ; (id : Nat → Nat)⟩)) := by
  induction ts generalizing acc with
  | nil => rfl
  | cons m ts ih =>
      simp only [parAllL_cons, List.map_cons]
      rw [ih]
      congr 1

lemma soupThreads_cren (ts : List Term) (ξ : Nat → Nat) :
    (soupThreads ts)⟨ξ; (id : Nat → Nat)⟩ =
      soupThreads (ts.map (fun m => m⟨ξ; (id : Nat → Nat)⟩)) := by
  rw [soupThreads_eq, soupThreads_eq, parAllL_cren]
  congr 1

/-- Congruence in the accumulator position of the thread fold. -/
lemma parAllL_acc_congr {acc acc' : Proc} (ts : List Term) (h : acc ≡ₚ acc') :
    parAllL acc ts ≡ₚ parAllL acc' ts := by
  induction ts generalizing acc acc' with
  | nil => exact h
  | cons m ts ih =>
      simp only [parAllL_cons]
      exact ih (congruence_par h ARS.Conv.refl)

/-- An outer parallel component folds into the accumulator. -/
lemma par_parAllL (X acc : Proc) (ts : List Term) :
    Proc.par X (parAllL acc ts) ≡ₚ parAllL (.par X acc) ts := by
  induction ts generalizing acc with
  | nil => exact ARS.Conv.refl
  | cons m ts ih =>
      simp only [parAllL_cons]
      refine ARS.conv_trans (ih (.par acc (.tm m))) (parAllL_acc_congr ts ?_)
      exact ARS.conv1 CongrProc.assoc

/-- The garbage seed of the soup body is invisible. -/
lemma par_soupThreads (X : Proc) (ts : List Term) :
    Proc.par X (soupThreads ts) ≡ₚ parAllL X ts := by
  rw [soupThreads_eq]
  refine ARS.conv_trans (par_parAllL X _ ts) (parAllL_acc_congr ts ?_)
  exact ARS.conv1 CongrProc.end

/-- Permuting the threads of a fold. -/
lemma parAllL_perm (acc : Proc) {ts ts' : List Term} (h : List.Perm ts ts') :
    parAllL acc ts ≡ₚ parAllL acc ts' := by
  induction h generalizing acc with
  | nil => exact ARS.Conv.refl
  | cons m _ ih =>
      simp only [parAllL_cons]
      exact ih _
  | swap m n ts =>
      simp only [parAllL_cons]
      refine parAllL_acc_congr ts ?_
      refine ARS.conv_trans (ARS.conv1i CongrProc.assoc) ?_
      refine ARS.conv_trans (congruence_par ARS.Conv.refl (ARS.conv1 CongrProc.par_sym)) ?_
      exact ARS.conv1 CongrProc.assoc
  | trans _ _ ih1 ih2 =>
      exact ARS.conv_trans (ih1 acc) (ih2 acc)

/-- Pointwise term congruence of the threads of a fold. -/
lemma parAllL_congr (acc : Proc) {ts ts' : List Term}
    (h : List.Forall₂ (CongrTerm .ex) ts ts') :
    parAllL acc ts ≡ₚ parAllL acc ts' := by
  induction h generalizing acc with
  | nil => exact ARS.Conv.refl
  | cons hm _ ih =>
      simp only [parAllL_cons]
      refine ARS.conv_trans (ih _) (parAllL_acc_congr _ ?_)
      exact congruence_par ARS.Conv.refl (ARS.conv1 (CongrProc.tm hm))

/-- Extruding a whole restriction block over a parallel composition. -/
lemma nuN_hoist (k : Nat) (Z : Proc) : ∀ Y : Proc,
    Proc.par (nuN k Z) Y ≡ₚ nuN k (.par Z (Y⟨(· + k); (id : Nat → Nat)⟩)) := by
  induction k with
  | zero =>
      intro Y
      simp only [nuN_zero]
      rw [pren_ext Y (ξ := (· + 0)) (ζ := (id : Nat → Nat)) (fun x => by simp), pren_id]
      exact ARS.Conv.refl
  | succ k ih =>
      intro Y
      simp only [nuN_succ]
      refine ARS.conv_trans (ARS.conv1 CongrProc.scope) (congruence_res ?_)
      refine ARS.conv_trans (ih (Y⟨((· + 1) : Nat → Nat); (id : Nat → Nat)⟩)) ?_
      rw [pren_comp,
        pren_ext Y (ξ := fun x => x + 1 + k) (ζ := (· + (k + 1)))
          (fun x => by show x + 1 + k = x + (k + 1); omega)]
      exact ARS.Conv.refl

/-- The adjacent binder transposition is `liftBinders` of the `exch` renaming. -/
lemma liftBinders_exch_ren (j : Nat) :
    ∀ x, liftBinders j exch_ren x = cswap j (j + 1) x := by
  intro x
  rcases Nat.lt_or_ge x j with hx | hx
  · rw [liftBinders_lt _ hx, cswap_ne (by omega) (by omega)]
  · rcases Nat.eq_or_lt_of_le hx with rfl | hx'
    · rw [liftBinders_ge _ (Nat.le_refl _), show j - j = 0 from by omega, exch_ren_zero,
        cswap_left]
  -- `rfl` substituted `x := j` in the branch above; below `j < x`.
    · rcases Nat.eq_or_lt_of_le hx' with heq1 | hx''
      · rw [← heq1, cswap_right, liftBinders_ge _ (by omega),
          show j + 1 - j = 1 from by omega, exch_ren_one]
        omega
      · rw [liftBinders_ge _ (by omega), show x - j = (x - j - 2) + 2 from by omega,
          exch_ren_add2, cswap_ne (by omega) (by omega)]
        omega

/-- Transposing two adjacent binders of a restriction block, via `exch` at depth. -/
lemma nuN_swap_adj {k j : Nat} (p : Proc) (h : j + 1 < k) :
    nuN k p ≡ₚ nuN k (p⟨cswap j (j + 1); (id : Nat → Nat)⟩) := by
  obtain ⟨a, rfl⟩ : ∃ a, k = a + (2 + j) := ⟨k - (2 + j), by omega⟩
  have h1 : ∀ q : Proc, nuN (a + (2 + j)) q = nuN a (.nu (.nu (nuN j q))) := by
    intro q
    rw [← nuN_comp a (2 + j) q, ← nuN_comp 2 j q]
    rfl
  rw [h1, h1]
  refine nuN_congr a ?_
  refine ARS.conv_trans (ARS.conv1 CongrProc.exch) ?_
  rw [csubst_exch, nuN_cren,
    pren_ext p (ξ := liftBinders j exch_ren) (ζ := cswap j (j + 1))
      (liftBinders_exch_ren j)]
  exact ARS.Conv.refl

private lemma nuN_swap_le {k : Nat} :
    ∀ (n j : Nat), j ≤ n → ∀ (p : Proc) (i : Nat), i ≤ j → j < k →
      nuN k p ≡ₚ nuN k (p⟨cswap i j; (id : Nat → Nat)⟩) := by
  intro n
  induction n with
  | zero =>
      intro j hjn p i hij _
      rw [pren_ext p (ξ := cswap i j) (ζ := (id : Nat → Nat)) (fun x => by
          simp only [cswap, id_eq]
          split_ifs <;> omega), pren_id]
      exact ARS.Conv.refl
  | succ n ihn =>
      intro j hjn p i hij hjk
      rcases Nat.eq_or_lt_of_le hij with rfl | hlt
      · rw [pren_ext p (ξ := cswap i i) (ζ := (id : Nat → Nat)) (fun x => by
            simp only [cswap, id_eq]
            split_ifs <;> omega), pren_id]
        exact ARS.Conv.refl
      · rcases Nat.eq_or_lt_of_le hlt with heq1 | hlt'
        · rw [pren_ext p (ξ := cswap i j) (ζ := cswap i (i + 1)) (fun x => by
            simp only [cswap]
            split_ifs <;> omega)]
          exact nuN_swap_adj p (by omega)
        · have step1 : nuN k p ≡ₚ nuN k (p⟨cswap (j - 1) j; (id : Nat → Nat)⟩) := by
            rw [pren_ext p (ξ := cswap (j - 1) j) (ζ := cswap (j - 1) ((j - 1) + 1))
              (fun x => by
                simp only [cswap]
                split_ifs <;> omega)]
            exact nuN_swap_adj p (by omega)
          have step2 := ihn (j - 1) (by omega)
            (p⟨cswap (j - 1) j; (id : Nat → Nat)⟩) i (by omega) (by omega)
          have step3 : nuN k
              ((p⟨cswap (j - 1) j; (id : Nat → Nat)⟩)⟨cswap i (j - 1); (id : Nat → Nat)⟩) ≡ₚ
              nuN k
              (((p⟨cswap (j - 1) j; (id : Nat → Nat)⟩)⟨cswap i (j - 1);
                (id : Nat → Nat)⟩)⟨cswap (j - 1) j; (id : Nat → Nat)⟩) := by
            rw [pren_ext
              ((p⟨cswap (j - 1) j; (id : Nat → Nat)⟩)⟨cswap i (j - 1); (id : Nat → Nat)⟩)
              (ξ := cswap (j - 1) j) (ζ := cswap (j - 1) ((j - 1) + 1)) (fun x => by
                simp only [cswap]
                split_ifs <;> omega)]
            exact nuN_swap_adj _ (by omega)
          refine ARS.conv_trans step1 (ARS.conv_trans step2 (ARS.conv_trans step3 ?_))
          rw [pren_comp, pren_comp,
            pren_ext p
              (ξ := fun x => cswap (j - 1) j (cswap i (j - 1) (cswap (j - 1) j x)))
              (ζ := cswap i j) (fun x => by
                simp only [cswap]
                split_ifs <;> omega)]
          exact ARS.Conv.refl

/-- Transposing any two binders of a restriction block. -/
lemma nuN_swap {k i j : Nat} (p : Proc) (hi : i < k) (hj : j < k) :
    nuN k p ≡ₚ nuN k (p⟨cswap i j; (id : Nat → Nat)⟩) := by
  rcases Nat.lt_or_ge i j with h | h
  · exact nuN_swap_le j j (Nat.le_refl j) p i (by omega) hj
  · rw [pren_ext p (ξ := cswap i j) (ζ := cswap j i) (fun x => by
      simp only [cswap]
      split_ifs <;> omega)]
    exact nuN_swap_le i i (Nat.le_refl i) p j (by omega) hi

/-! ## N1: every process is congruent to its prenex form -/

/-- Every process is structurally congruent to the soup form of its prenex configuration. -/
theorem prenex_sound (P : Proc) : P ≡ₚ soupForm (prenex P) := by
  induction P with
  | tm m =>
      show Proc.tm m ≡ₚ Proc.par (.tm (.pure .one)) (.tm m)
      refine ARS.conv_trans (ARS.conv1i CongrProc.end) ?_
      exact ARS.conv1 CongrProc.par_sym
  | nu p ih =>
      exact congruence_res ih
  | par p q ihp ihq =>
      rcases hp : prenex p with ⟨kp, tsp⟩
      rcases hq : prenex q with ⟨kq, tsq⟩
      rw [hp] at ihp
      rw [hq] at ihq
      rw [prenex_par, hp, hq]
      refine ARS.conv_trans (congruence_par ihp ihq) ?_
      show Proc.par (nuN kp (soupThreads tsp)) (nuN kq (soupThreads tsq)) ≡ₚ
        nuN (kp + kq) (soupThreads
          (tsp.map (fun m => m⟨shiftAbove kp kq; (id : Nat → Nat)⟩) ++
            tsq.map (fun m => m⟨(· + kp); (id : Nat → Nat)⟩)))
      refine ARS.conv_trans (ARS.conv1 CongrProc.par_sym) ?_
      refine ARS.conv_trans (nuN_hoist kq (soupThreads tsq) (nuN kp (soupThreads tsp))) ?_
      rw [nuN_cren]
      refine ARS.conv_trans (nuN_congr kq (ARS.conv1 CongrProc.par_sym)) ?_
      refine ARS.conv_trans (nuN_congr kq
        (nuN_hoist kp _ (soupThreads tsq))) ?_
      rw [nuN_comp, show kq + kp = kp + kq from by omega]
      refine nuN_congr (kp + kq) ?_
      rw [pren_ext (soupThreads tsp) (ξ := liftBinders kp (· + kq)) (ζ := shiftAbove kp kq)
          (fun x => by
            simp only [liftBinders, shiftAbove]
            split_ifs <;> omega),
        soupThreads_cren, soupThreads_cren, soupThreads_append]
      exact par_soupThreads _ _

/-! ## N3: the soup equivalence maps back to structural congruence -/

lemma soupG_congr {c c' : Config} (h : SoupG c c') : soupForm c ≡ₚ soupForm c' := by
  cases h with
  | @perm k ts ts' hperm =>
      exact nuN_congr k (parAllL_perm _ hperm)
  | @congr k ts ts' hcongr =>
      exact nuN_congr k (parAllL_congr _ hcongr)
  | @garbage k ts =>
      refine nuN_congr k ?_
      show soupThreads ts ≡ₚ parAllL (.par (.tm (.pure .one)) (.tm (.pure .one))) ts
      refine parAllL_acc_congr ts ?_
      exact ARS.conv1i CongrProc.end
  | @swap k ts i j hi hj =>
      show nuN k (soupThreads ts) ≡ₚ
        nuN k (soupThreads (ts.map (fun m => m⟨cswap i j; (id : Nat → Nat)⟩)))
      rw [← soupThreads_cren]
      exact nuN_swap _ hi hj

/-- Soup-equivalent configurations denote structurally congruent processes. -/
theorem soupEquiv_congr {c c' : Config} (h : SoupEquiv c c') :
    soupForm c ≡ₚ soupForm c' :=
  ARS.conv_img soupForm SoupG (fun _ _ h => soupG_congr h) c c' h

/-! ## The characterization -/

/-- Structural congruence is exactly the soup equivalence of prenex forms. -/
theorem congruence_iff_soup {P Q : Proc} :
    P ≡ₚ Q ↔ SoupEquiv (prenex P) (prenex Q) := by
  constructor
  · exact congruence_soup
  · intro h
    exact ARS.conv_trans (prenex_sound P)
      (ARS.conv_trans (soupEquiv_congr h) (ARS.conv_sym (prenex_sound Q)))

end TLLC.Process
